projects:
  template:
    schemaPath: graphql/schema.json
    includes:
      - graphql/**/*.graphql
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: swift
        generatedFileName: API.swift
        docsFilePath: graphql
        maxDepth: 2
extensions:
  amplify:
    version: 3